# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 16:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('desc', models.TextField(blank=True)),
                ('ext_guest_authors', models.TextField(blank=True)),
                ('number', models.IntegerField(default=1)),
                ('cover', models.ImageField(blank=True, upload_to=b'issues')),
                ('thumb', models.ImageField(blank=True, upload_to=b'issues')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to=b'issues')),
                ('thumb', models.ImageField(blank=True, upload_to=b'issues')),
                ('subtitles', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zines.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('pic', models.ImageField(blank=True, upload_to=b'users')),
                ('thumb', models.ImageField(blank=True, upload_to=b'users')),
                ('location', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zines.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Zine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name=b'Published since')),
                ('show_author', models.BooleanField(default=True)),
                ('external', models.BooleanField(default=False, verbose_name=b'Externally hosted')),
                ('submissions_open', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('primary_language', models.CharField(default=b'English', max_length=300)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('contact_email', models.CharField(blank=True, max_length=200)),
                ('submission_email', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'Published until')),
                ('website', models.URLField(blank=True)),
                ('cover', models.ImageField(upload_to=b'covers')),
                ('thumb', models.ImageField(blank=True, upload_to=b'covers')),
                ('locale', models.CharField(blank=True, max_length=500)),
                ('authors', models.ManyToManyField(to='zines.Profile')),
                ('tags', models.ManyToManyField(blank=True, to='zines.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='guest_authors',
            field=models.ManyToManyField(blank=True, to='zines.Profile'),
        ),
        migrations.AddField(
            model_name='issue',
            name='zine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zines.Zine'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='page',
            order_with_respect_to='issue',
        ),
        migrations.AlterOrderWithRespectTo(
            name='issue',
            order_with_respect_to='zine',
        ),
    ]
