# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('hideIdentity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('member_since', models.DateField(verbose_name=b'Member since')),
                ('name', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Zine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(verbose_name=b'Published since')),
                ('show_author', models.BooleanField(default=True)),
                ('tagline', models.CharField(max_length=500)),
                ('end_date', models.DateField(blank=True, verbose_name=b'Published until')),
                ('authors', models.ManyToManyField(through='zines.Authorship', to='zines.User')),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zines.User'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='zine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zines.Zine'),
        ),
    ]
