# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zine',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Published until'),
        ),
        migrations.AlterField(
            model_name='zine',
            name='start_date',
            field=models.DateField(verbose_name=b'Published since'),
        ),
        migrations.AlterField(
            model_name='zine',
            name='tagline',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
