# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='zines.Profile'),
        ),
    ]
