# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zine',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name=b'Published since'),
        ),
    ]
