# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0002_auto_20161229_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zine',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='hideIdentity',
            field=models.BooleanField(default=False, verbose_name=b'Hide Identity'),
        ),
    ]
