# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0003_auto_20161229_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField()),
                ('guest_authors', models.ManyToManyField(blank=True, to='zines.User')),
                ('zine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zines.Zine')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='issue',
            order_with_respect_to='zine',
        ),
    ]
