# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0004_auto_20161229_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
