# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0005_issue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
