# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0008_auto_20161229_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='locale',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
