# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0010_zine_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
