# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0011_issue_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='zine',
            name='submission_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='zine',
            name='submissions_open',
            field=models.BooleanField(default=False),
        ),
    ]
