# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0012_auto_20170101_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zine',
            name='zine_pic',
            field=models.FileField(upload_to=b'zines/'),
        ),
    ]
