# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0013_auto_20170103_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zine',
            old_name='zine_pic',
            new_name='cover',
        ),
    ]
