# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0014_auto_20170103_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.FileField(upload_to=b'covers'),
        ),
        migrations.AlterField(
            model_name='zine',
            name='cover',
            field=models.FileField(upload_to=b'covers'),
        ),
    ]
