# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0016_auto_20170116_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='contact_email',
        ),
    ]
