# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0018_auto_20170117_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member_since',
        ),
    ]
