# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0020_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_since',
            field=models.DateField(auto_now=True),
        ),
    ]
