# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0023_auto_20170125_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ext_guest_authors',
            field=models.TextField(blank=True),
        ),
    ]
