# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0024_auto_20170206_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zine',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
