# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0025_auto_20170207_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.CharField(max_length=200)),
                ('parent_tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zines.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='zine',
            name='tags',
            field=models.ManyToManyField(to='zines.Tag'),
        ),
    ]
