# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0026_auto_20170208_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zines.Tag'),
        ),
    ]
