# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0028_auto_20170208_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, upload_to=b'/users'),
        ),
        migrations.AlterField(
            model_name='zine',
            name='tags',
            field=models.ManyToManyField(blank=True, to='zines.Tag'),
        ),
    ]
