# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0030_auto_20170216_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to=b'users'),
        ),
    ]
