# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0031_auto_20170217_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=b'users'),
        ),
    ]
